#!/bin/bash

echo "🚀 Chat Platform - MongoDB Atlas Setup"
echo "======================================"
echo ""

echo "📋 Pasos para configurar MongoDB Atlas:"
echo ""
echo "1. Ve a https://www.mongodb.com/atlas"
echo "2. Crea una cuenta gratuita"
echo "3. Crea un cluster M0 (gratuito)"
echo "4. Configura Database Access:"
echo "   - Username: chat_user"
echo "   - Password: chat_password123"
echo "   - Privileges: Read and write to any database"
echo ""
echo "5. Configura Network Access:"
echo "   - Add IP Address: Allow access from anywhere (0.0.0.0/0)"
echo ""
echo "6. Obtén la cadena de conexión:"
echo "   - Database → Connect → Connect your application"
echo "   - Copia la cadena de conexión"
echo ""
echo "7. Actualiza el archivo de configuración:"
echo "   - Edita backend/src/config/mongodb-atlas.ts"
echo "   - Reemplaza la cadena de conexión"
echo ""
echo "8. Inicia la aplicación:"
echo "   cd backend && npm run dev"
echo ""

echo "🔧 Comandos útiles:"
echo ""
echo "# Verificar conexión a Atlas"
echo "curl http://localhost:3001/health"
echo ""
echo "# Ver logs del backend"
echo "cd backend && npm run dev"
echo ""
echo "# Ver logs del frontend"
echo "cd frontend && npm run dev"
echo ""

echo "🎉 ¡Tu plataforma de chat con MongoDB Atlas estará lista!"
echo ""
echo "Funcionalidades disponibles:"
echo "• 💬 Chat en tiempo real con MongoDB Atlas"
echo "• 👥 Gestión de grupos"
echo "• 📁 Transferencia de archivos"
echo "• ✏️ Edición colaborativa de documentos"
echo "• 🔐 Autenticación segura"
echo "• 👤 Gestión de usuarios y permisos"
echo "• 🗄️ Base de datos MongoDB Atlas (Cloud)"
echo ""
